using System;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;
using UnityEngine.EventSystems;

namespace HikanyanLibrary.UISystem.Editor
{
    public static class UIAuthoring
    {
        [MenuItem("GameObject/Hikanyan/UI/Create UI Bootstrap", false, 0)]
        public static void CreateBootstrap()
        {
            var root = new GameObject("UI System", typeof(UIManager), typeof(UIBootstrap), typeof(UIBackHandler));
            Undo.RegisterCreatedObjectUndo(root, "Create UI Bootstrap");
            var manager = root.GetComponent<UIManager>();
            if (!AssetDatabase.IsValidFolder("Assets/UI")) AssetDatabase.CreateFolder("Assets", "UI");
            const string path = "Assets/UI/UICatalog.asset";
            var catalog = AssetDatabase.LoadAssetAtPath<UICatalog>(path);
            if (catalog == null)
            {
                catalog = ScriptableObject.CreateInstance<UICatalog>();
                AssetDatabase.CreateAsset(catalog, path);
            }
            manager.Catalog = catalog;
            root.GetComponent<UIBootstrap>().Initialize();
            if (UnityEngine.Object.FindFirstObjectByType<EventSystem>() == null)
            {
                var events = new GameObject("EventSystem", typeof(EventSystem));
                events.transform.SetParent(root.transform, false);
                var inputType = Type.GetType("UnityEngine.InputSystem.UI.InputSystemUIInputModule, Unity.InputSystem");
                if (inputType != null)
                {
                    var module = events.AddComponent(inputType);
                    inputType.GetMethod("AssignDefaultActions")?.Invoke(module, null);
                }
                else events.AddComponent<StandaloneInputModule>();
            }
            Selection.activeGameObject = manager.DefaultRoot.Find(UILayer.Page.ToString()).gameObject;
            EditorUtility.SetDirty(manager);
            AssetDatabase.SaveAssets();
        }

        public static string BuildKeys(UICatalog catalog, string ns)
        {
            if (!CodeGenerationValidation.IsNamespace(ns)) throw new ArgumentException("Invalid namespace.");
            var errors = catalog.Validate().ToArray();
            if (errors.Length != 0) throw new InvalidOperationException(string.Join("\n", errors));
            var source = new StringBuilder($"// <auto-generated />\nusing HikanyanLibrary.UISystem;\nnamespace {ns}\n{{\npublic static class GameUI\n{{\n");
            foreach (var screen in catalog.Screens.OrderBy(x => x.Id, StringComparer.Ordinal))
            {
                if (!CodeGenerationValidation.IsIdentifier(screen.Id)) throw new InvalidOperationException($"Use a C# identifier for id '{screen.Id}'.");
                if (screen.Prefab == null) throw new InvalidOperationException($"{screen.Id}: assign a prefab when generating keys. Runtime-only Addressable catalogs may use hand-written UIKey declarations.");
                var type = screen.Prefab.GetType();
                var args = type.GetInterfaces().FirstOrDefault(x => x.IsGenericType && x.GetGenericTypeDefinition() == typeof(IUIArguments<>));
                if (args == null) throw new InvalidOperationException($"{screen.Id}: presenter must declare IUIArguments<T>.");
                var result = type.GetInterfaces().FirstOrDefault(x => x.IsGenericType && x.GetGenericTypeDefinition() == typeof(IUIResult<>));
                string Name(Type t) => "global::" + t.FullName.Replace('+', '.');
                var keyType = result == null ? $"UIKey<{Name(args.GenericTypeArguments[0])}>" :
                    $"UIDialogKey<{Name(args.GenericTypeArguments[0])}, {Name(result.GenericTypeArguments[0])}>";
                source.AppendLine($"    public static readonly {keyType} {screen.Id} = {keyType}.For<{Name(type)}>(\"{screen.Id}\");");
            }
            return source.Append("}\n}\n").ToString();
        }
    }

    [CustomEditor(typeof(UICatalog))]
    public sealed class UICatalogEditor : UnityEditor.Editor
    {
        private string _namespace = "Game.UI";
        public override void OnInspectorGUI()
        {
            DrawDefaultInspector();
            var catalog = (UICatalog)target;
            foreach (var error in catalog.Validate()) EditorGUILayout.HelpBox(error, MessageType.Error);
            _namespace = EditorGUILayout.TextField("Keys namespace", _namespace);
            if (!GUILayout.Button("Generate GameUI.g.cs")) return;
            try
            {
                var source = UIAuthoring.BuildKeys(catalog, _namespace);
                var path = EditorUtility.SaveFilePanelInProject("Generated keys", "GameUI.g", "cs", "Select generated code location.");
                if (string.IsNullOrEmpty(path)) return;
                if (File.Exists(path) && !File.ReadAllText(path).StartsWith("// <auto-generated />", StringComparison.Ordinal))
                    throw new InvalidOperationException("Select a generated file. User-authored code will not be replaced.");
                if (!File.Exists(path) || File.ReadAllText(path) != source) { File.WriteAllText(path, source); AssetDatabase.ImportAsset(path); }
            }
            catch (Exception exception) { EditorUtility.DisplayDialog("UI validation", exception.Message, "OK"); }
        }
    }
}
